// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
. . . . . . . e c 7 . . . . . . 
. . . . e e e c 7 7 e e . . . . 
. . c e e e e c 7 e 2 2 e e . . 
. c e e e e e c 6 e e 2 2 2 e . 
. c e e e 2 e c c 2 4 5 4 2 e . 
c e e e 2 2 2 2 2 2 4 5 5 2 2 e 
c e e 2 2 2 2 2 2 2 2 4 4 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 4 2 e 
. e e e 2 2 2 2 2 2 2 2 2 4 e . 
. 2 e e 2 2 2 2 2 2 2 2 4 2 e . 
. . 2 e e 2 2 2 2 2 4 4 2 e . . 
. . . 2 2 e e 4 4 4 2 e e . . . 
. . . . . 2 2 e e e e . . . . . 
`;
            case "image2":return img`
....................................
....................................
....................................
...............ccffff...............
..............cddbbbf...............
.......ffffffcddbbbf................
.....ffbbbbbbbbbbbbbcfff.......ccccc
...ffbbbbbbbbcbcbbbbbcccff....cdbbbc
..fbbbbbbbbbbcbbcbbbbcccccfffcddbbc.
.fbcbbbbbbbbbbcbcbbbbccccccccbdbbf..
.fbbbbbbbfffbbcbbbbbccccccccccbbcf..
.ffbb1111fffbbcbbbbcccccccbcffbccf..
..ff111111111bbbbccccccbbbcc..fbbcf.
....ccccccc111bdbbbfddbccc.....ffbbf
........ccccccfbdbbbfcc..........fff
...............ffffff...............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "anim1":return [img`
..............fffcc.............
..............fcbddcc...........
...............fbbddcc..........
...............fcbbccf..........
..ccc.........ffccccccfffff.....
..cbbcc....fffcbbbbcbbbbbbbff...
...cbbdc.ffcccbbbbcbcbbbbbbbbf..
...fbbdcfcccccbbbcbcbbffbbbbbbff
....fbbffcccccbbbbbcb1ff11bbbcbf
....fcbbcccccccbbbbb11111111bbbf
....fcccccccccccbbbb11cc33111bf.
...fcbbffbdbcccccbbb111c13cccf..
...fbbf..ccddddcfbbbc111c31cf...
..fbbf.....ccdccbbdbf111cccf....
..fff........ccbbdcfcccc........
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1ff1111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc111c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`, img`
..............fffc..............
..............fbddcc............
..ccc.........ffbddbc...........
..cbbc.........fcbbccf..........
...cbdc.......ffccccccfffffff...
...fbdc....fffcbbbbbbbbbbbbbcff.
....fbdc.ffcccbbbbbbcbbbbbbbbbcf
....fcdffcccccbbbcbcbbbffbbbbcbf
....fcbbccccccbbbcbcbbbff1111bbf
...fcbbccccccccbbbcbb11111111bf.
...fbbfffcccccccbbbb11bc33cccf..
..fbbf..cbdbcccccbbb111c131cf...
..fff....cbdddddccbbc111c33f....
..........ccbddccbbdf1111ff.....
............ccfbbbdfccccc.......
..............fffff.............
`, img`
..............fffcc.............
..............fbbddc............
...............fbbddc...........
ccc............fcbbccf..........
cbbcc.........ffccccccffffff....
.cbbdc.....fffcbbbbbbbbbbbbbff..
.fbbddc..ffcccbbbbcbcbbbbbbbbbff
..fbbdfffcccccbbbcbcbbffbbbbbcbf
..fcbbbcccccccbbbcbcb1ff1111bbbf
..fccbcccccccccbbbbbb11111111bf.
.fcbbfffccccccccbbbb11cc33cccf..
.fbbf...cbdbcccccbbb111c131cf...
fbbf.....ccdddddfbbbc111c33f....
fff........ccddfbbdbf1111ff.....
.............cfbbdbfccccc.......
..............fffff.............
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
